'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    'navigation.portfolio': 'Portfolio',
    'navigation.toggleTheme': 'Switch to {mode} mode',
    'navigation.home': 'Home',
    'navigation.about': 'About',
    'navigation.experience': 'Experience',
    'navigation.skills': 'Skills',
    'navigation.projects': 'Projects',
    'navigation.contact': 'Contact',
    'verticalNav.hero': 'Home',
    'verticalNav.about': 'About',
    'verticalNav.experience': 'Experience',
    'verticalNav.skills': 'Skills',
    'verticalNav.projects': 'Projects',
    'verticalNav.contact': 'Contact',
    'hero.greeting': 'Hi, I\'m {name}',
    'hero.title': 'Senior Software Engineer',
    'hero.subtitle': 'I create beautiful, performant web experiences that users love.',
    'hero.description': 'I create beautiful, performant web experiences that users love. Specializing in React, TypeScript, and modern web technologies.',
    'hero.badge': 'Available for Work',
    'hero.cta.primary': 'Get In Touch',
    'hero.cta.secondary': 'View My Work',
    'hero.actions.viewWork': 'View My Work',
    'hero.actions.contact': 'Get In Touch',
    'hero.stats.projects': 'Projects',
    'hero.stats.years': 'Years',
    'hero.stats.satisfaction': 'Client Satisfaction',
    'hero.skills': 'React,TypeScript,Next.js,Node.js,UI/UX',
    'about.title': 'About Me',
    'about.subtitle': 'Passionate about creating exceptional user experiences through innovative design and cutting-edge technology.',
    'about.sectionTitle': 'Building Digital Experiences',
    'about.description1': 'With over 5 years of experience in frontend development, I specialize in creating responsive, accessible, and performant web applications. My passion lies in translating complex requirements into elegant, user-friendly solutions.',
    'about.description2': 'I believe in the power of clean code, thoughtful design, and continuous learning. When I\'m not coding, you\'ll find me exploring new technologies, contributing to open source, or sharing knowledge with the developer community.',
    'about.stats.title': 'Key Metrics',
    'about.stats.projects': 'Projects',
    'about.stats.years': 'Years',
    'about.stats.satisfaction': 'Client Satisfaction',
    'about.interests.title': 'What I Love',
    'about.interests.items': 'Clean Code,User Experience,Innovation,Collaboration',
    'experience.title': 'Experience',
    'experience.subtitle': 'A journey through my professional growth, showcasing key achievements and the technologies that shaped my career.',
    'experience.achievements.title': 'Key Achievements',
    'experience.technologies.title': 'Technologies Used',
    'skills.title': 'Skills & Expertise',
    'skills.subtitle': 'A comprehensive overview of my technical skills and professional capabilities, built through years of hands-on experience and continuous learning.',
    'skills.technical.title': 'Technical Skills',
    'skills.categories.frontend': 'Frontend Development',
    'skills.categories.backend': 'Backend & Database',
    'skills.categories.tools': 'Tools & Technologies',
    'skills.categories.design': 'Design & UX',
    'skills.softSkills.title': 'Soft Skills & Professional Qualities',
    'skills.softSkills.items': 'Team Leadership,Problem Solving,Code Review,Mentoring,Agile/Scrum,Communication,Project Management,Technical Writing',
    'projects.title': 'Featured Projects',
    'projects.subtitle': 'A showcase of my most impactful projects, demonstrating expertise in full-stack development, AI/ML, and modern web technologies.',
    'projects.status.live': 'Live',
    'projects.status.development': 'In Development',
    'projects.status.archived': 'Archived',
    'projects.categories.fullstack': 'Full Stack',
    'projects.categories.aiml': 'AI/ML',
    'projects.categories.realtime': 'Real-time',
    'projects.categories.mobile': 'Mobile',
    'projects.categories.designsystem': 'Design System',
    'projects.categories.blockchain': 'Blockchain',
    'projects.features': 'Key Features:',
    'projects.technologies.title': 'Technologies',
    'projects.actions.code': 'Code',
    'projects.actions.liveDemo': 'Live Demo',
    'projects.actions.viewAll': 'View All Projects',
    'projects.ecommerce.title': 'E-Commerce Platform',
    'projects.ecommerce.description': 'Full-stack e-commerce solution with real-time inventory management, payment processing, and admin dashboard.',
    'projects.ecommerce.features': 'Real-time updates,Payment integration,Admin dashboard,Inventory management,User authentication',
    'projects.ai.title': 'AI-Powered Analytics',
    'projects.ai.description': 'Machine learning platform that analyzes user behavior and provides actionable insights for business optimization.',
    'projects.ai.features': 'Machine learning models,Data visualization,Real-time processing,API integration,Cloud deployment',
    'projects.chat.title': 'Real-time Chat App',
    'projects.chat.description': 'Scalable chat application with WebSocket support, file sharing, and end-to-end encryption.',
    'projects.chat.features': 'WebSocket integration,File sharing,End-to-end encryption,Message history,User presence',
    'projects.mobile.title': 'Mobile Banking App',
    'projects.mobile.description': 'Cross-platform mobile application for banking services with biometric authentication and transaction management.',
    'projects.mobile.features': 'Biometric auth,Transaction management,Real-time notifications,Offline support,Secure API',
    'projects.design.title': 'Design System',
    'projects.design.description': 'Comprehensive design system with reusable components, documentation, and design tokens for consistent UI.',
    'projects.design.features': 'Component library,Design tokens,Documentation,Accessibility,Theme support',
    'projects.defi.title': 'DeFi Dashboard',
    'projects.defi.description': 'Decentralized finance dashboard for tracking cryptocurrency portfolios and DeFi protocols.',
    'projects.defi.features': 'Wallet integration,Portfolio tracking,DeFi protocols,Real-time prices,Transaction history',
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Ready to collaborate or have a question? I\'d love to hear from you. Let\'s create something amazing together.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.actions.downloadResume': 'Download Resume',
    'contact.actions.followMe': 'Follow Me',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Message sent successfully! I\'ll get back to you soon.',
    'contact.form.error': 'Failed to send message. Please try again.',
    'contact.validation.firstName.required': 'First name is required.',
    'contact.validation.firstName.minLength': 'First name must be at least 2 characters.',
    'contact.validation.firstName.maxLength': 'First name must not exceed 50 characters.',
    'contact.validation.lastName.required': 'Last name is required.',
    'contact.validation.lastName.minLength': 'Last name must be at least 2 characters.',
    'contact.validation.lastName.maxLength': 'Last name must not exceed 50 characters.',
    'contact.validation.email.required': 'Email is required.',
    'contact.validation.email.invalid': 'Please enter a valid email address.',
    'contact.validation.subject.required': 'Subject is required.',
    'contact.validation.subject.minLength': 'Subject must be at least 5 characters.',
    'contact.validation.subject.maxLength': 'Subject must not exceed 100 characters.',
    'contact.validation.message.required': 'Message is required.',
    'contact.validation.message.minLength': 'Message must be at least 10 characters.',
    'contact.validation.message.maxLength': 'Message must not exceed 1000 characters.',
    'error.general': 'An unexpected error occurred. Please try again.',
    'error.retry': 'Retry',
    'error.reset': 'Reset Application',
    'error.sectionError': 'Failed to load {section} section. Please try again.',
    'error.particleSystem': 'Particle system encountered an error and has been disabled.',
  },
  es: {
    'navigation.portfolio': 'Portafolio',
    'navigation.toggleTheme': 'Cambiar a modo {mode}',
    'navigation.home': 'Inicio',
    'navigation.about': 'Acerca de',
    'navigation.experience': 'Experiencia',
    'navigation.skills': 'Habilidades',
    'navigation.projects': 'Proyectos',
    'navigation.contact': 'Contacto',
    'verticalNav.hero': 'Inicio',
    'verticalNav.about': 'Acerca de',
    'verticalNav.experience': 'Experiencia',
    'verticalNav.skills': 'Habilidades',
    'verticalNav.projects': 'Proyectos',
    'verticalNav.contact': 'Contacto',
    'hero.greeting': 'Hola, soy {name}',
    'hero.title': 'Ingeniero de Software Senior',
    'hero.subtitle': 'Creo experiencias web hermosas y performantes que los usuarios aman.',
    'hero.description': 'Creo experiencias web hermosas y performantes que los usuarios aman. Especializado en React, TypeScript y tecnologías web modernas.',
    'hero.badge': 'Disponible para Trabajar',
    'hero.cta.primary': 'Ponerse en Contacto',
    'hero.cta.secondary': 'Ver Mi Trabajo',
    'hero.actions.viewWork': 'Ver Mi Trabajo',
    'hero.actions.contact': 'Ponerse en Contacto',
    'hero.stats.projects': 'Proyectos',
    'hero.stats.years': 'Años',
    'hero.stats.satisfaction': 'Satisfacción del Cliente',
    'hero.skills': 'React,TypeScript,Next.js,Node.js,UI/UX',
    'about.title': 'Acerca de Mí',
    'about.subtitle': 'Apasionado por crear experiencias de usuario excepcionales a través de diseño innovador y tecnología de vanguardia.',
    'about.sectionTitle': 'Construyendo Experiencias Digitales',
    'about.description1': 'Con más de 5 años de experiencia en desarrollo frontend, me especializo en crear aplicaciones web responsivas, accesibles y performantes. Mi pasión radica en traducir requisitos complejos en soluciones elegantes y fáciles de usar.',
    'about.description2': 'Creo en el poder del código limpio, el diseño reflexivo y el aprendizaje continuo. Cuando no estoy programando, me encontrarás explorando nuevas tecnologías, contribuyendo al código abierto o compartiendo conocimiento con la comunidad de desarrolladores.',
    'about.stats.title': 'Métricas Clave',
    'about.stats.projects': 'Proyectos',
    'about.stats.years': 'Años',
    'about.stats.satisfaction': 'Satisfacción del Cliente',
    'about.interests.title': 'Lo Que Me Encanta',
    'about.interests.items': 'Código Limpio,Experiencia de Usuario,Innovación,Colaboración',
    'experience.title': 'Experiencia',
    'experience.subtitle': 'Un viaje a través de mi crecimiento profesional, mostrando logros clave y las tecnologías que dieron forma a mi carrera.',
    'experience.achievements.title': 'Logros Clave',
    'experience.technologies.title': 'Tecnologías Utilizadas',
    'skills.title': 'Habilidades y Experiencia',
    'skills.subtitle': 'Una visión integral de mis habilidades técnicas y capacidades profesionales, construidas a través de años de experiencia práctica y aprendizaje continuo.',
    'skills.technical.title': 'Habilidades Técnicas',
    'skills.categories.frontend': 'Desarrollo Frontend',
    'skills.categories.backend': 'Backend y Base de Datos',
    'skills.categories.tools': 'Herramientas y Tecnologías',
    'skills.categories.design': 'Diseño y UX',
    'skills.softSkills.title': 'Habilidades Blandas y Cualidades Profesionales',
    'skills.softSkills.items': 'Liderazgo de Equipo,Resolución de Problemas,Revisión de Código,Mentoría,Agile/Scrum,Comunicación,Gestión de Proyectos,Escritura Técnica',
    'projects.title': 'Proyectos Destacados',
    'projects.subtitle': 'Una muestra de mis proyectos más impactantes, demostrando experiencia en desarrollo full-stack, IA/ML y tecnologías web modernas.',
    'projects.status.live': 'En Vivo',
    'projects.status.development': 'En Desarrollo',
    'projects.status.archived': 'Archivado',
    'projects.categories.fullstack': 'Full Stack',
    'projects.categories.aiml': 'IA/ML',
    'projects.categories.realtime': 'Tiempo Real',
    'projects.categories.mobile': 'Móvil',
    'projects.categories.designsystem': 'Sistema de Diseño',
    'projects.categories.blockchain': 'Blockchain',
    'projects.features': 'Características Clave:',
    'projects.technologies.title': 'Tecnologías',
    'projects.actions.code': 'Código',
    'projects.actions.liveDemo': 'Demo en Vivo',
    'projects.actions.viewAll': 'Ver Todos los Proyectos',
    'projects.ecommerce.title': 'Plataforma E-Commerce',
    'projects.ecommerce.description': 'Solución e-commerce full-stack con gestión de inventario en tiempo real, procesamiento de pagos y panel de administración.',
    'projects.ecommerce.features': 'Actualizaciones en tiempo real,Integración de pagos,Panel de administración,Gestión de inventario,Autenticación de usuarios',
    'projects.ai.title': 'Analytics con IA',
    'projects.ai.description': 'Plataforma de machine learning que analiza el comportamiento del usuario y proporciona insights accionables para optimización empresarial.',
    'projects.ai.features': 'Modelos de machine learning,Visualización de datos,Procesamiento en tiempo real,Integración de API,Despliegue en la nube',
    'projects.chat.title': 'App de Chat en Tiempo Real',
    'projects.chat.description': 'Aplicación de chat escalable con soporte WebSocket, intercambio de archivos y cifrado de extremo a extremo.',
    'projects.chat.features': 'Integración WebSocket,Intercambio de archivos,Cifrado de extremo a extremo,Historial de mensajes,Presencia de usuario',
    'projects.mobile.title': 'App de Banca Móvil',
    'projects.mobile.description': 'Aplicación móvil multiplataforma para servicios bancarios con autenticación biométrica y gestión de transacciones.',
    'projects.mobile.features': 'Autenticación biométrica,Gestión de transacciones,Notificaciones en tiempo real,Soporte offline,API segura',
    'projects.design.title': 'Sistema de Diseño',
    'projects.design.description': 'Sistema de diseño integral con componentes reutilizables, documentación y tokens de diseño para UI consistente.',
    'projects.design.features': 'Biblioteca de componentes,Tokens de diseño,Documentación,Accesibilidad,Soporte de temas',
    'projects.defi.title': 'Dashboard DeFi',
    'projects.defi.description': 'Dashboard de finanzas descentralizadas para rastrear portafolios de criptomonedas y protocolos DeFi.',
    'projects.defi.features': 'Integración de billetera,Seguimiento de portafolio,Protocolos DeFi,Precios en tiempo real,Historial de transacciones',
    'contact.title': 'Ponerse en Contacto',
    'contact.subtitle': '¿Listo para colaborar o tienes una pregunta? Me encantaría saber de ti. Creemos algo increíble juntos.',
    'contact.info.title': 'Información de Contacto',
    'contact.info.email': 'Correo',
    'contact.info.phone': 'Teléfono',
    'contact.info.location': 'Ubicación',
    'contact.actions.downloadResume': 'Descargar Currículum',
    'contact.actions.followMe': 'Sígueme',
    'contact.form.firstName': 'Nombre',
    'contact.form.lastName': 'Apellido',
    'contact.form.email': 'Correo',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.submitting': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado exitosamente! Te responderé pronto.',
    'contact.form.error': 'Error al enviar mensaje. Por favor, inténtalo de nuevo.',
    'contact.validation.firstName.required': 'El nombre es requerido.',
    'contact.validation.firstName.minLength': 'El nombre debe tener al menos 2 caracteres.',
    'contact.validation.firstName.maxLength': 'El nombre no debe exceder 50 caracteres.',
    'contact.validation.lastName.required': 'El apellido es requerido.',
    'contact.validation.lastName.minLength': 'El apellido debe tener al menos 2 caracteres.',
    'contact.validation.lastName.maxLength': 'El apellido no debe exceder 50 caracteres.',
    'contact.validation.email.required': 'El correo es requerido.',
    'contact.validation.email.invalid': 'Por favor, ingresa un correo válido.',
    'contact.validation.subject.required': 'El asunto es requerido.',
    'contact.validation.subject.minLength': 'El asunto debe tener al menos 5 caracteres.',
    'contact.validation.subject.maxLength': 'El asunto no debe exceder 100 caracteres.',
    'contact.validation.message.required': 'El mensaje es requerido.',
    'contact.validation.message.minLength': 'El mensaje debe tener al menos 10 caracteres.',
    'contact.validation.message.maxLength': 'El mensaje no debe exceder 1000 caracteres.',
    'error.general': 'Ocurrió un error inesperado. Por favor, inténtalo de nuevo.',
    'error.retry': 'Reintentar',
    'error.reset': 'Reiniciar Aplicación',
    'error.sectionError': 'Error al cargar la sección {section}. Por favor, inténtalo de nuevo.',
    'error.particleSystem': 'El sistema de partículas encontró un error y ha sido deshabilitado.',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
